server:
  port: 9001
spring:
  application:
    name: shadow-mall-security-oauth2-server
  datasource:
    url: jdbc:mysql://localhost:3306/shadow_mall_userDB?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect